### PR TITLE
CTest integration

### PR DESCRIPTION
**Pull request by ZehMatt**
A little follow up on #4, this adds the tests to CMake which provides a better cross platform way to run the tests and I added the GitHub Actions CI integration. I tried to stay as close as possible to the pre-existing script, right now it only covers Ubuntu with GCC and Clang and Windows. We could use docker images to run the tests on more platforms but I think this is a good starting point.

I had to comment out the static_assert's as the size relies on the alignment also which is not the same on each platform/compiler, to ensure same alignment we would need to specify packing or modify the compiler settings to be consistent across the board.

As for the pre-existing tests nothing changed.

A workflow run from my fork: https://github.com/ZehMatt/sfl-library/actions/runs/7502293888

### CODE REVIEW

**Comment by slavenf** [comment]
Thank you very much for this, but I am currently not ready to merge this into my repository.

Namely, I am currently doing huge refactoring on tests and refactoring and improvements on the library itself. I hope I will finish it in 2-3 months. Before that I am not ready to merge your changes in my repository.

And here is another very important thing: I am testing each container with different allocators and with very specific compiler flags. That's why I have created those bash scripts in `test` directory. 

I am testing this library on CentOS 7 with gcc 4.8 and clang 3.4. You wouldn't believe me, but During library development I have encountered a lot of situations when gcc 4.8 reports error during compilation but gcc 12 compiles without errors (using same flags, including `-std=c++11` flag).

I am testing this library on Arch Linux with the latest gcc and clang using `-std=c++11`, `-std=c++14`, `-std=c++17` and `-std=c++20` flags. During library development I have encountered several situations that both gcc 4.8 and gcc 12, both with `-std=c++11` flag, compiles without errors, but gcc 12 with `-std=c++20` flag reports error during compilation.

As you can see, there is a lot of possible combinations. My test scripts are covering all these combinations.

I am also testing everything with valgrind. When I started working on this library I have encountered a lot of problems that valgrind successfully detected even though all assertions passed. Running each with valgrind is extremly important.

My plan is the following: When I finish refactoring (I hope in 2-3 months), I will improve test scripts for Linux and I will create test scripts for Windows and Visual C++ compiler. After that it would be nice to have CentOS 7 and Arch Linux in GitHub actions instead of Ubuntu. Just to note, I do not like CMake and I won't use it for testing. I am considerig GNU make or maybe xmake, but for now, it is mush easier for me to use one script.

**Comment by ZehMatt** [comment]
Fair enough, however I don't think that having this on-top of your custom tests would actually hurt it. Once you finalized the changes I can definitely look into covering that all also on the CI. However I understand, so I'm fine if you close this PR.

**Comment by slavenf** [comment]
@ZehMatt Still interested into this?

If yes, please continue reading.

I am currently working on branch [develop](https://github.com/slavenf/sfl-library/tree/develop). I have rewritten and reorganized all tests. I have the following top-level test scripts:
- `test_all_arch_linux.sh`
- `test_all_centos_7.sh`
- `test_all_msvc.bat`

These scripts run all combinations of tests. These scripts are using GNU makefiles:
- `makefile`
- `makefile.msvc`

The first one is intended to be used on Linux with GCC and Clang. The second one is for Windows and Visual C++.

Both makefiles have the following targets:
- `check`
- `check_small_vector` 
- `check_small_flat_set`
- `check_small_flat_map`
- ...
- `clean`

I often use `make check_XXX` because I work on a single container at the time. Makefiles are a little bit unusual, but they are doing exactly what I want. Makefiles are writen to make full rebuild each time, not incremental build. I always *want* full rebuild. Makefiles are very simple and I don't know whether it is possible to achive the same level of simplicity with CMake.

So, please take a look onto branch [develop-with-github-actions](https://github.com/slavenf/sfl-library/tree/develop-with-github-actions). I have added some github actions there.

If you have some ides, comments, whatever, please tell me.

**Comment by ZehMatt** [comment]
Looks promising, as for the make vs CMake part, not exactly sure what to think of it, as long it runs the tests I don't really mind what it is, as for consuming the library the CMake contribution of mine works nicely as it is. I will definitely try to contribute if I run into something that would block me.

**Comment by slavenf** [comment]
Ok. Thanks. For now, I will continue with the current solution.

**Pull request closed without merging**
